### ISSUE TITLE
RXSubscriptionManager

### ISSUE THREAD

**Issue by Rainer-Lang** [MFlisar/RXBus#4]
Why don't you use `CompositeSubscription` instead of `HashSet<Subscription>`? You only have to use "clear()" for unsubscribe.
Is there a reason?

**Comment by MFlisar** [comment]
No. I was working with rx for a few weeks and then decided to write this... Did not know about `CompositeSubscription` yet. Sounds like I would fit just as good as the `HashSet`...

**Comment by Rainer-Lang** [comment]
Thanks

**Comment by MFlisar** [comment]
Version 0.6 does use this class now...

**Comment by MFlisar** [comment]
Just saw, that `clear` is not working as intented but `unsubscribe` does... So again, a new release (0.8) was made for this

**Comment by Rainer-Lang** [comment]
After unsubscribe nothing could be added anymore to the CompositeSubscription.

**Comment by MFlisar** [comment]
No problem, the `CompositeSubscription` is removed as well from the internal `HashMap`...

I saw, that calling `clear` will result in not unsubscribing all child subscriptions... Calling `unsubscribe` does work though

**Comment by Rainer-Lang** [comment]
Some were still there, after clear?

**Comment by MFlisar** [comment]
All... I have a dialog and make a subscription in `onCreate` and unsubscribe in `onDestroy` and whenever I open the dialog, it adds a new subscription and never unsubscribes it. `unsubscribe` does work though...

This should not be the case, if I read the docs of `clear` though. I found a few examples for `CompositeSubscription` and all call `unsubscribe`.
