### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by Rainer-Lang** [MFlisar/RXBus#5]
How to solve this?
`Warning:com.michaelflisar.rxbus.rx.RxValve$ValveSubscriber: can't find referenced class rx.internal.util.RxJavaPluginUtils`

**Comment by MFlisar** [comment]
This is no problem with this library per se I think, looks like you are obfuscating your RX functions...

I normally use a setup like following and don't have any problems (proguard rules are applied with the extra compile dependency (use the same versions, more here: https://github.com/artem-zinnatullin/RxJavaProGuardRules):

```
compile 'io.reactivex:rxjava:1.1.9'
compile 'com.artemzin.rxjava:proguard-rules:1.1.9.0'
```

Does that help?

**Comment by Rainer-Lang** [comment]
@MFlisar Thanks.
