### ISSUE TITLE
Strange behaviour...lately

### ISSUE THREAD

**Issue by Rainer-Lang** [MFlisar/RXBus#6]
I use the RXBus with String-keys. It was working fine.
But since yesterday I recognized that I run into key-events where I shouldn't.

I use this (an example):
`RXBus.get().sendEvent("Account saved", BusKeysDef.SAVED_ACCOUNT);`
and I also run into:
`RXSubscriptionManager.addSubscription(this,
RXBusBuilder.create(String.class).withBusMode(RXBusMode.Main)
                        .withKey(BusKeysDef.CREATED_ACCOUNT)
                        .withOnNext(s -> invalidateOptionsMenu())
                        .buildSubscription()
);`

Sorry for the formatting

**Comment by Rainer-Lang** [comment]
I couldn't tell if it's since yesterday or not. I even changed a lot - but nothing with the RXBus....
Should I try integer instead of String keys?

**Comment by Rainer-Lang** [comment]
Maybe something with the version of Rxjava....

**Comment by MFlisar** [comment]
I'll update the dependencies when I come home tomorrow, there were a few updates in the meantime. Not sure if this is the issue for you though...

What do you actually mean? That you retrieve wrong events in subscriptions? Events that do not match the key?

**Comment by Rainer-Lang** [comment]
I retrieve events which don't match the key.

**Comment by Rainer-Lang** [comment]
And some I should get for a key, but I don't get them.

**Comment by MFlisar** [comment]
As you can see in the RXBus class I use two simple Hashmaps with keys of type `Class` or of the type `RXQueueKey`. As far as I see, if you get now wrong events, this means that something in the hash code and equals functions of the `RXQueueKey` is wrong (as this is used to distinguish between which event should be send to which observable) in the `RXBus` class....

Using integer or strings as keys does not make any difference, the `RXQueueKey` is wrapping those two to offer a common class that the bus can use to avoid writing every function for each type again...

I looked at the `RXQueueKey` class and can't see any problems in the hash and equal functions now....

I'll have a closer look tomorrow...

**Comment by MFlisar** [comment]
Just saw it. Hash code calculation is wrong in the `RXQueueKey` class. I'll think this may be the cause for your problem... I'll fix that tomorrow...

**Comment by Rainer-Lang** [comment]
Thanks.

**Comment by Rainer-Lang** [comment]
@MFlisar Please take a look: https://medium.com/@amitshekhar/android-app-optimization-using-arraymap-and-sparsearray-f2b4e2e3dc47#.mq79neynt

**Comment by MFlisar** [comment]
Actually, sending events to the corresponding subjects is delegated via the `HashMaps` and the corresponding keys of type `RXQueueKey` (https://github.com/MFlisar/RXBus/blob/master/lib/src/main/java/com/michaelflisar/rxbus/rx/RXQueueKey.java).

This means, getting the correct `Subject` is only depending on the `RXQueueKey`, which again means, it's only depending on the hash and equal function of this class:

https://github.com/MFlisar/RXBus/blob/master/lib/src/main/java/com/michaelflisar/rxbus/rx/RXQueueKey.java#L36
https://github.com/MFlisar/RXBus/blob/master/lib/src/main/java/com/michaelflisar/rxbus/rx/RXQueueKey.java#L56

I still don't see any mistake there.

I uploaded a new version with the adjustments for the newest rx java version (some things in the `RxValve` had changed and I did not update the repo yet) and some other changes. Maybe this was a problem for you...

**Rest**
- I don't see anything that could cause emitting events to the wrong subscriptions, the links above show the code that are relevant imho (the hash and equal function), maybe you see a mistake in there?
- Have not yet changed `HashMap` to `ArrayMap`, I'm not sure if I should. It would mean adding a dependency to the support library... Which currently isn't necessary...

**Additional**

I'll add a short readme about some breaking changes in the next few minutes to the readme.... I removed some interfaces and changed one main interface.... The usage of the library get's simplier with this changes though...

**Comment by Rainer-Lang** [comment]
I'll try it tomorrow and give feedback.

**Comment by MFlisar** [comment]
This is what you have to do: https://github.com/MFlisar/RXBus/blob/master/MIGRATION.md Release will be available shortly

**Comment by Rainer-Lang** [comment]
`RXSubscriptionManager.addSubscription` isn't static anymore (unsubscribe too). Is there a reason?

**Comment by MFlisar** [comment]
I was mixing singleton and static functions... Just wanted to clear that (did that already long ago in my code). Of course, there is no reason why I couldn't offer static functions.

Added them again in v0.7...

**Comment by Rainer-Lang** [comment]
@MFlisar && v0.7 -> Thanks :)

About the behaviour: Maybe I found something.
I have a BaseActivity and an Activity (extends BaseActivity). In both classes I created RXBus-subscriptions. This was causing problems like I wrote.
Now I put ALL RXBus-subscriptions out of my BaseActivity and in the "normal" Activity. Now all went fine.

I have some RXBus-subscriptions which I want to have for all activities, so I would like to put them in the BaseActivity to not duplicate code.

**Comment by MFlisar** [comment]
Fast workaround would be writing a function in the base class like `initRXBusSubscriptions()` and call it in your sub activities...

I'm using base classes as well and make subscriptions in them (and in the inherited classes as well) and did not have a problem yet. I'm rarely using the keys though, mostly I bind everything to classes only

I have no idea why you get wrong events, but losing events may happen, because you may create keys for the `BaseActivity` instead of the extended `Activity` when calling `RXBusBuilder.queue(...)`?

**Comment by Rainer-Lang** [comment]
I used it the same way like you.

> I have no idea why you get wrong events, but losing events may happen, because you may create keys for the BaseActivity instead of the extended Activity when calling RXBusBuilder.queue(...)?

Could you make an example? Maybe this is what went wrong....

**Comment by MFlisar** [comment]
Sorry, I was wrong. Of course the builder creates keys for the event class and the `Integer` key you pass in.

I was thinking about the `RXSubscriptionManager` when I wrote that...

**Comment by MFlisar** [comment]
I've added what you are doing to my demo here: https://github.com/MFlisar/RXBus/blob/master/demo/src/main/java/com/michaelflisar/rxbus/demo/PauseAwareActivity.java#L29 Seems to work so far.

Can you somehow reproduce your problem in the demo?

**Comment by Rainer-Lang** [comment]
I use `.queue(this)`

**Comment by MFlisar** [comment]
I added this to the demo. And added two subscriptions to https://github.com/MFlisar/RXBus/blob/master/demo/src/main/java/com/michaelflisar/rxbus/demo/PauseAwareActivity.java#L29

And I send a few events in `onCreate`, before/after `onResume` and before/after `onPause` in the `DemoActivity` to the bus (see this function: https://github.com/MFlisar/RXBus/blob/master/demo/src/main/java/com/michaelflisar/rxbus/demo/DemoActivity.java#L184), the two subscriptions in the base activity are still working as expected...

**Comment by Rainer-Lang** [comment]
I tried your example. It's working.
Now play with it. ;)

**Comment by Rainer-Lang** [comment]
I can't reproduce the error.
I changed your example to fit better. Also no error.

I'll close this issue for now. If I have any news about this, I'll inform you.
Thanks for your support.
